export const skills = [
  { category: 'Languages',  items: ['Python', 'JavaScript', 'TypeScript', 'Java', 'C', 'SQL'] },
  { category: 'Frontend',   items: ['React', 'Next.js', 'HTML5', 'CSS3', 'Tailwind CSS'] },
  { category: 'Backend',    items: ['Node.js', 'Express', 'FastAPI', 'REST APIs'] },
  { category: 'Databases',  items: ['PostgreSQL', 'MongoDB', 'Firebase', 'Supabase'] },
  { category: 'AI / ML',    items: ['TensorFlow', 'OpenCV', 'MediaPipe', 'LLMs', 'Pandas', 'Gemini'] },
  { category: 'Tools',      items: ['Git', 'GitHub', 'Postman', 'Power BI', 'Tableau', 'Vite'] },
]

export const experience = [
  {
    period: '2026',
    company: 'Vayu Aarambh Innovations',
    role: 'Software Developer',
    desc: 'Built scalable full-stack modules for AI + IoT products using Next.js, Node.js and Firebase. Collaborated with cross-functional teams to deliver production-ready features.',
    tags: ['Next.js', 'Node.js', 'Firebase', 'IoT'],
  },
  {
    period: 'Jan 2026 – May 2026',
    company: 'Besant Technologies',
    role: 'Full Stack Development Intern',
    desc: 'Completed 16-week hands-on internship in end-to-end web application development. Built real-time industry projects covering front-end (HTML, CSS, JS, React), back-end, database design, deployment and full-stack technologies.',
    tags: ['React', 'JavaScript', 'Node.js', 'Full Stack'],
  },
  {
    period: 'Internship',
    company: 'CodSoft',
    role: 'Machine Learning Intern',
    desc: 'Developed and evaluated ML models on real-world datasets, end-to-end from data preprocessing to evaluation.',
    tags: ['Python', 'ML', 'Pandas', 'Scikit-learn'],
  },
  {
    period: 'Internship',
    company: 'Edunet Foundation',
    role: 'AI Intern',
    desc: 'Built a deep learning model for forest fire detection using image classification for an early-warning safety system.',
    tags: ['TensorFlow', 'OpenCV', 'Deep Learning'],
  },
]

export const projects = [
  {
    num: '01',
    title: 'Real-Time AI Voice Agent for Interactive Interviews',
    desc: 'AI interview system using Gemini LLM, WebRTC and Vapi SDK with adaptive questioning and automated feedback. Implements speech processing, dynamic prompts and performance evaluation pipeline.',
    tags: ['Gemini LLM', 'WebRTC', 'Vapi SDK', 'NLP'],
    link: 'https://github.com/bhargav158/forest_fire_detection',
    highlight: true,
    award: '🏆 2nd Best Paper — IC-AISMART 2025',
    isNew: false,
  },
  {
    num: '02',
    title: 'VoxFlow AI — Voice-Powered AI Assistant',
    desc: 'Built at HacBLR Hackathon — a real-time voice AI assistant with natural language understanding, speech-to-text and AI-generated responses. Features low-latency voice pipeline and interactive conversation flow.',
    tags: ['Voice AI', 'LLM', 'Speech-to-Text', 'React'],
    link: 'https://github.com/bhargav158/voxflow-ai',
    highlight: false,
    award: '⚡ HacBLR Hackathon Project',
    isNew: true,
  },
  {
    num: '03',
    title: 'FinTrack — Personal Finance Tracker',
    desc: 'Full-stack personal finance management app to track income, expenses and budgets with visual analytics. Features real-time dashboards, category-wise spending insights and monthly reports.',
    tags: ['React', 'Node.js', 'MongoDB', 'Chart.js'],
    link: 'https://github.com/bhargav158/fintrack',
    highlight: false,
    award: null,
    isNew: true,
  },
  {
    num: '04',
    title: 'AI Agent — Task Automation System',
    desc: 'Intelligent AI agent application that automates repetitive tasks using LLM-powered decision making. Supports multi-step workflows, tool use and autonomous execution pipelines.',
    tags: ['LLM', 'AI Agents', 'Python', 'Automation'],
    link: 'https://github.com/bhargav158/ai-agent-app',
    highlight: false,
    award: null,
    isNew: true,
  },
  {
    num: '05',
    title: 'VRMS — Vehicle Rental Management System',
    desc: 'Full-stack vehicle rental management platform with booking, fleet tracking, user management and billing. Features admin dashboard, real-time availability and automated invoice generation.',
    tags: ['Full Stack', 'React', 'Node.js', 'PostgreSQL'],
    link: 'https://github.com/bhargav158/vrms-vehicle-rental',
    highlight: false,
    award: null,
    isNew: true,
  },
  {
    num: '06',
    title: 'AI-Powered Connections for Matching Profiles',
    desc: 'ML-based recommendation engine using behavioral and preference similarity scoring with feature extraction and ranking model for accurate user profile matching.',
    tags: ['Machine Learning', 'Recommendation', 'Python'],
    link: 'https://github.com/bhargav158',
    highlight: false,
    award: '📄 Published — IJARESM (IF 8.5)',
    isNew: false,
  },
  {
    num: '07',
    title: 'AI Therapist',
    desc: 'NLP-based conversational assistant for context-aware mental health support with intent detection, context memory and empathetic response generation.',
    tags: ['NLP', 'Conversational AI', 'Intent Detection'],
    link: 'https://github.com/bhargav158',
    highlight: false,
    award: null,
    isNew: false,
  },
  {
    num: '08',
    title: 'Clinique Health Tree',
    desc: 'Full-stack healthcare booking platform with appointment scheduling, responsive UI and backend APIs for patient data management.',
    tags: ['Full Stack', 'Node.js', 'REST API', 'React'],
    link: 'https://github.com/bhargav158',
    highlight: false,
    award: null,
    isNew: false,
  },
  {
    num: '09',
    title: 'Carbon Footprint Tracker',
    desc: 'Web app to calculate carbon emissions and generate personalized eco insights using usage patterns and emission factors.',
    tags: ['React', 'Data Viz', 'Sustainability'],
    link: 'https://github.com/bhargav158',
    highlight: false,
    award: null,
    isNew: false,
  },
]

export const publications = [
  {
    type: 'journal' as const,
    title: 'AI-Powered Connections for Matching Profiles',
    venue: 'IJARESM · ISSN: 2455-6211 · Impact Factor: 8.536 · Volume 13, Issue 7 · July 2025',
    award: null,
  },
  {
    type: 'conference' as const,
    title: 'A Real-Time AI Voice Agent for Interactive Interviews',
    venue: 'IC-AISMART 2025 — AICTE-Sponsored International Conference · JSS Academy, Bengaluru',
    award: '🏆 2nd Best Paper Award',
  },
]

export const achievements = [
  { icon: '🏆', title: '2nd Best Paper — IC-AISMART 2025', desc: 'For "A Real-Time AI Voice Agent for Interactive Interviews" at AICTE-sponsored conference.' },
  { icon: '⚡', title: 'HacBLR Hackathon', desc: 'Built VoxFlow AI — a real-time voice AI assistant at Bangalore\'s HacBLR hackathon.' },
  { icon: '🎖️', title: 'Certificate of Appreciation — IC-AISMART', desc: 'Recognized for outstanding AI project presentation at JSS Academy, Bengaluru.' },
  { icon: '🤖', title: 'Google Agentic AI Hackathon', desc: 'Certificate of Achievement for innovative agentic AI development.' },
  { icon: '⚡', title: 'Code-6-Craze Hackathon', desc: 'Built and shipped a real-time solution under competitive hackathon conditions.' },
  { icon: '🚀', title: 'ISRO Hackathon', desc: 'National-level participation in ISRO\'s space-tech innovation challenge.' },
]

export const chatResponses: Record<string, string> = {
  default: "Hi! I'm Bhargav's portfolio bot 🤖 Ask me about his skills, projects, experience, or how to contact him!",
  hello: "Hey there! 👋 I'm Bhargav's AI assistant. Ask me anything about his work!",
  hi: "Hey there! 👋 I'm Bhargav's AI assistant. Ask me anything about his work!",
  skills: "Bhargav is skilled in:\n• **Languages:** Python, JavaScript, Java, C, SQL\n• **Frontend:** React, Next.js, Tailwind\n• **Backend:** Node.js, Express, FastAPI\n• **AI/ML:** TensorFlow, OpenCV, LLMs, Gemini\n• **Databases:** PostgreSQL, MongoDB, Firebase",
  projects: "Bhargav has built 9 projects:\n1. 🎙️ AI Voice Interview Agent (Published!)\n2. 🔊 VoxFlow AI — HacBLR Hackathon\n3. 💰 FinTrack — Finance Tracker\n4. 🤖 AI Agent Task Automation\n5. 🚗 VRMS — Vehicle Rental System\n6. 🤝 Profile Matching ML Engine\n7. 🧠 AI Therapist\n8. 🏥 Clinique Health Tree\n9. 🌱 Carbon Footprint Tracker",
  experience: "Bhargav has worked at:\n• **Besant Technologies** — Full Stack Dev Intern (Jan 2026–Present)\n• **Vayu Aarambh Innovations** — Software Developer (2022–2026)\n• **CodSoft** — ML Intern\n• **Edunet Foundation** — AI Intern\n\nFinal year at AMC Engineering College with a 9.0 GPA!",
  contact: "You can reach Bhargav at:\n📧 gowdabhargav3@gmail.com\n📞 +91 80738 55488\n💼 linkedin.com/in/bhargav-gowda-61039b2a6\n🐙 github.com/bhargav158",
  education: "Bhargav is a final year student at **AMC Engineering College, Bangalore** pursuing B.E. in AI & ML with a GPA of **9.0/10**.",
  publications: "Bhargav has 2 publications:\n1. 📄 *AI-Powered Connections* — IJARESM (Impact Factor: 8.5)\n2. 🏆 *AI Voice Agent for Interviews* — IC-AISMART 2025 (**2nd Best Paper!**)",
  gpa: "Bhargav has a GPA of **9.0/10** at AMC Engineering College! 🎓",
  award: "Bhargav won **2nd Best Paper Award** at IC-AISMART 2025 for his work on AI Voice Agents! 🏆",
  hire: "Bhargav is actively looking for **Software Engineer, Full Stack, Backend, and AI roles**! 🚀\n\nReach out at: gowdabhargav3@gmail.com",
  voxflow: "VoxFlow AI is Bhargav's hackathon project from **HacBLR** — a real-time voice AI assistant with speech-to-text, LLM responses and natural conversation flow. github.com/bhargav158/voxflow-ai 🔊",
  fintrack: "FinTrack is Bhargav's personal finance tracker — built with React, Node.js and MongoDB. github.com/bhargav158/fintrack 💰",
  agent: "Bhargav's AI Agent app automates repetitive tasks using LLM-powered decision making. github.com/bhargav158/ai-agent-app 🤖",
  vrms: "VRMS is a Vehicle Rental Management System — full-stack with booking, fleet tracking and billing. github.com/bhargav158/vrms-vehicle-rental 🚗",
  besant: "Bhargav is currently a **Full Stack Development Intern at Besant Technologies** (Jan 2026–Present), working on real-time industry full-stack projects under the VTU Free Internship Program.",
}
